credentials:
  usernames:
    katie:
      name: Katie
      email: katie.bom@gmail.com
      password: $2b$12$jv5M/QjJoJMrSLa9bacsVuR1ic2DOmJuY7MUJyCSFQ0M0oktRowT6
      role: admin
      created_at: '2026-05-09'
    katie.bom@gmail.com:
      name: Katie
      email: katie.bom@gmail.com
      password: $2b$12$jv5M/QjJoJMrSLa9bacsVuR1ic2DOmJuY7MUJyCSFQ0M0oktRowT6
      role: admin
      created_at: '2026-05-09'
cookie:
  name: aplb_dashboard_auth
  key: aplb-secret-2026-please-change-this-in-production-7f3kx9
  expiry_days: 30
preauthorized:
  emails: []
spreadsheet_id: 12TcKAcvzN5mY-STukvR2F1ZO_dLjOEY6tmqk_VKGeGc
